(cl:defpackage lslidar_ch128x1_msgs-msg
  (:use )
  (:export
   "<LSLIDARCHLAYER>"
   "LSLIDARCHLAYER"
   "<LSLIDARCHPACKET>"
   "LSLIDARCHPACKET"
   "<LSLIDARCHPOINT>"
   "LSLIDARCHPOINT"
   "<LSLIDARCHSCAN>"
   "LSLIDARCHSCAN"
   "<LSLIDARCHSCANUNIFIED>"
   "LSLIDARCHSCANUNIFIED"
   "<LSLIDARCHSWEEP>"
   "LSLIDARCHSWEEP"
  ))

