// Generated by gencpp from file lslidar_ch128x1_msgs/LslidarChScan.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CH128X1_MSGS_MESSAGE_LSLIDARCHSCAN_H
#define LSLIDAR_CH128X1_MSGS_MESSAGE_LSLIDARCHSCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lslidar_ch128x1_msgs/LslidarChPoint.h>

namespace lslidar_ch128x1_msgs
{
template <class ContainerAllocator>
struct LslidarChScan_
{
  typedef LslidarChScan_<ContainerAllocator> Type;

  LslidarChScan_()
    : altitude(0.0)
    , points()  {
    }
  LslidarChScan_(const ContainerAllocator& _alloc)
    : altitude(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef double _altitude_type;
  _altitude_type altitude;

   typedef std::vector< ::lslidar_ch128x1_msgs::LslidarChPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::lslidar_ch128x1_msgs::LslidarChPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> const> ConstPtr;

}; // struct LslidarChScan_

typedef ::lslidar_ch128x1_msgs::LslidarChScan_<std::allocator<void> > LslidarChScan;

typedef boost::shared_ptr< ::lslidar_ch128x1_msgs::LslidarChScan > LslidarChScanPtr;
typedef boost::shared_ptr< ::lslidar_ch128x1_msgs::LslidarChScan const> LslidarChScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator1> & lhs, const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator2> & rhs)
{
  return lhs.altitude == rhs.altitude &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator1> & lhs, const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_ch128x1_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c77dc6b198843a42fa2ff9c4aa233e";
  }

  static const char* value(const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c77dc6b198843aULL;
  static const uint64_t static_value2 = 0x42fa2ff9c4aa233eULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_ch128x1_msgs/LslidarChScan";
  }

  static const char* value(const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Altitude of all the points within this scan\n"
"float64 altitude\n"
"\n"
"# The valid points in this scan sorted by azimuth\n"
"# from 0 to 359.99\n"
"LslidarChPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: lslidar_ch128x1_msgs/LslidarChPoint\n"
"# Time when the point is captured\n"
"float64 time\n"
"\n"
"# Converted distance in the sensor frame\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"# Raw measurement from Leishen Ch\n"
"float64 vertical_angle\n"
"float64 azimuth\n"
"float64 distance\n"
"float64 intensity\n"
"uint16  line\n"
;
  }

  static const char* value(const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LslidarChScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_ch128x1_msgs::LslidarChScan_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lslidar_ch128x1_msgs::LslidarChPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CH128X1_MSGS_MESSAGE_LSLIDARCHSCAN_H
